export const products = [
    {
      id: 1,
      name: "Men's Streetwear Fashion Style Big Pocket Cotton Long Sleeve Shirt Blue / XL",
      category: "Baju",
      price: 30,
      image: "/images/products/baju-1.png",
      isCart: false,
      description: "This shirt features a vibrant and eye-catching color and a solid pattern that will give you a happy feeling. Its long sleeve design makes it an ideal choice for men. The turn-down collar adds to comfort and stylish look. Its versatile design and great fit make it an ideal choice for casual occasions. Specifications Style: Casual Sleeve Style: Regular Sleeve Length(cm): Full Shirts Type: Casual Shirts Pattern Type: Solid Origin: CN(Origin) Model Number: C6112 Material: Cotton Item T",
    },
    {
      id: 2,
      name: "Air Max Man( US 40-44 )",
      category: "Sepatu",
      price: 30,
      image: "/images/products/airmax.png",
      isCart: false,
      description: "Nike Air is our iconic innovation that uses pressurized air in a durable, flexible membrane to provide lightweight cushioning. The air compresses on impact and then immediately returns to its original shape and volume, ready for the next impact.",
    },
    {
      id: 3,
      name: "Men's Streetwear Fashion Style Big Pocket Cotton Long Sleeve Shirt Gray / XL",
      category: "Baju",
      price: 25,
      image: "/images/products/baju-3.png",
      isCart: false,
      description: "Navy Blue Preppy Long Sleeve Polyester Plaid Shirt Non-Stretch Spring/Fall Men Tops",
    },
    {
      id: 4,
      name: "Ted Baker Mens SeyII Slim Fit Plain Trouser, Navy - Size 34W/32L",
      category: "Celana",
      price: 100,
      image: "/images/products/celana-4.png",
      isCart: false,
      description: "Rugged, functional, and to the point. The Operator Utility Shirt has a military look with a metropolitan fit and finish. The durable stone gray cotton shirt weight canvas is sure to be a favorite back to well-worn denim.",
    },
    {
      id: 5,
      name: "Batch Freelancer Men's Button Down Shirt in Aluminum Gray",
      category: "Baju",
      price: 10,
      image: "/images/products/baju-5.png",
      isCart: false,
      description: "White Casual Short Sleeve Cotton Plain Top Embellished Non-Stretch Summer Men Tops",
    },
    {
      id: 6,
      name: "Converse Chuck Taylor (CM 26-28.5)",
      category: "Sepatu",
      price: 15,
      image: "/images/products/converse.png",
      isCart: false,
      description: "The high-top silhouette was composed of a rubber sole and canvas upper, with a cushioned insole, arch and heel support as well as its now-iconic diamond tread pattern, designed for increased traction.",
    },
    {
      id: 7,
      name: " Patek Philippe Perpetual Calendar Chronograph 5270P-001",
      category: "Jam",
      price: 200,
      image: "/images/products/patekfilipe.png",
      isCart: false,
      description: "The Perpetual Calendar Chronograph is the nadir of complicated watchmaking at Patek Philippe. This model is the first Perpetual Calendar Chronograph to feature a platinum case, which pairs exceedingly well with a salmon dial. Those with an interest in Patek Philippe watches will understand that platinum models are usually more coveted than their gold counterparts, and the 5270P-001 is no exception.",
    }


  ];